## Exercícios: listas, tuplas, sets e dicionários

Os problemas seguir estão relacionados com o conteúdo da Aula:

* [Listas, tuplas, sets e dicionários](https://colab.research.google.com/drive/1xymB3-OzGTeVWRbWYQWZ5kwzM2Wg_voB?usp=sharing)

**Problema 1**. Dada uma lista de números inteiros consecutivos, crie uma nova lista com os elementos pares da primeira lista usando slices de listas. Por exemplo, se a lista original for `[1, 2, 3, 4, 5, 6]`, a nova lista deve ser `[2, 4, 6]`.

In [19]:
# código aqui

**Problema 2**. Dada uma lista de números inteiros de 0 a 9, crie uma nova lista com os elementos da primeira lista invertidos usando slices de listas. Por exemplo, se a lista original for `[0 ,1 ,2 ,3 ,4 ,5 ,6 ,7 ,8 ,9]`, a nova lista deve ser `[9 ,8 ,7 ,6 ,5 ,4 ,3 ,2 ,1 ,0]`.

In [20]:
# código aqui

**Problema 3**. Dada uma lista de números, crie uma nova lista com o quadrado de cada número usando a função `map()` e a função `lambda`. Por exemplo, se a lista original for `[1, 2, 3, 4]`, a nova lista deve ser `[1, 4, 9, 16]`.

In [21]:
# código aqui

**Problema 4**. Dadas duas listas de números, crie uma nova lista com a soma dos elementos correspondentes de cada lista usando a função `zip()` e a função `lambda`. Por exemplo, se as listas originais forem `[1, 2, 3] `e `[4, 5, 6]`, a nova lista deve ser `[5, 7, 9]`.

In [22]:
# código aqui

**Problema 5**. Dadas duas listas de números inteiros, crie uma nova lista com os elementos da primeira lista elevados aos elementos da segunda lista usando a função `map()` e a função `lambda`. Por exemplo, se as listas originais forem `[2, 3, 4]` e `[5, 6, 7]`, a nova lista deve ser `[32, 729, 16384]`.

In [ ]:
# código aqui

**Problema 6**. Dada uma lista de números inteiros positivos e negativos, crie uma nova lista com apenas os números positivos usando a função `filter()` e a função `lambda`. Por exemplo, se a lista original for `[-2, -1, 0, 1, 2]`, a nova lista deve ser `[0, 1, 2]`.

In [ ]:
# código aqui

Dado um dicionário com as quantidades de diferentes frutas, retorne a soma total de todas as frutas. Por exemplo, se o dicionário for
```python
frutas = {
    "maçã": 5,
    "banana": 3,
    "laranja": 7,
    "abacaxi": 2
}
```
a soma total das frutas será: 17.

In [ ]:
# código aqui

Dado um dicionário com o nome dos alunos e suas notas de uma turma, retorne a média da turma. Por exemplo, se o dicionário for
```python
notas = {
    "João": 7.5,
    "Maria": 8.2,
    "Pedro": 6.8,
    "Ana": 9.1
}
```
a média da turma será: 7.9

In [ ]:
# código aqui

**Problema 7**. Dado um conjunto contendo os números de 1 a 10, encontre a interseção entre esse conjunto e outro conjunto contendo os números de 5 a 15.

In [ ]:
# código aqui